@file:Suppress("unused")

package com.chrynan.colors.extension

import com.chrynan.colors.Color
import com.chrynan.colors.hex

val Color.Companion.ALICE_BLUE by lazy { hex("#F0F8FF") }
val Color.Companion.ANTIQUE_WHITE by lazy { hex("#FAEBD7") }
val Color.Companion.AQUA_BLUE by lazy { hex("#00FFFF") }
val Color.Companion.AQUAMARINE by lazy { hex("#7FFFD4") }
val Color.Companion.AZURE by lazy { hex("#F0FFFF") }
val Color.Companion.BEIGE by lazy { hex("#F5F5DC") }
val Color.Companion.BISQUE by lazy { hex("#FFE4C4") }
val Color.Companion.BLANCHED_ALMOND by lazy { hex("#FFEBCD") }
val Color.Companion.BLUE by lazy { hex("#0000FF") }
val Color.Companion.BLUE_VIOLET by lazy { hex("#8A2BE2") }
val Color.Companion.BROWN by lazy { hex("#A52A2A") }
val Color.Companion.BURLY_WOOD by lazy { hex("#DEB887") }
val Color.Companion.CADET_BLUE by lazy { hex("#5F9EA0") }
val Color.Companion.CHARTREUSE by lazy { hex("#7FFF00") }
val Color.Companion.CHOCOLATE by lazy { hex("#D2691E") }
val Color.Companion.CORAL by lazy { hex("#FF7F50") }
val Color.Companion.CORNFLOWER_BLUE by lazy { hex("#6495ED") }
val Color.Companion.CORNSILK by lazy { hex("#FFF8DC") }
val Color.Companion.CRIMSON by lazy { hex("#DC143C") }
val Color.Companion.CYAN by lazy { hex("#00FFFF") }
val Color.Companion.DARK_BLUE by lazy { hex("#00008B") }
val Color.Companion.DARK_CYAN by lazy { hex("#008B8B") }
val Color.Companion.DARK_GOLDEN_ROD by lazy { hex("#B8860B") }
val Color.Companion.DARK_GRAY by lazy { hex("#A9A9A9") }
val Color.Companion.DARK_GREEN by lazy { hex("#006400") }
val Color.Companion.DARK_KHAKI by lazy { hex("#BDB76B") }
val Color.Companion.DARK_MAGENTA by lazy { hex("#8B008B") }
val Color.Companion.DARK_OLIVE_GREEN by lazy { hex("#556B2F") }
val Color.Companion.DARK_ORANGE by lazy { hex("#FF8C00") }
val Color.Companion.DARK_ORCHID by lazy { hex("#9932CC") }
val Color.Companion.DARK_RED by lazy { hex("#8B0000") }
val Color.Companion.DARK_SALMON by lazy { hex("#E9967A") }
val Color.Companion.DARK_SEA_GREEN by lazy { hex("#8FBC8F") }
val Color.Companion.DARK_SLATE_BLUE by lazy { hex("#483D8B") }
val Color.Companion.DARK_SLATE_GRAY by lazy { hex("#2F4F4F") }
val Color.Companion.DARK_TURQUOISE by lazy { hex("#00CED1") }
val Color.Companion.DARK_VIOLET by lazy { hex("#9400D3") }
val Color.Companion.DEEP_PINK by lazy { hex("#FF1493") }
val Color.Companion.DEEP_SKY_BLUE by lazy { hex("#00BFFF") }
val Color.Companion.DIM_GRAY by lazy { hex("#696969") }
val Color.Companion.DODGER_BLUE by lazy { hex("#1E90FF") }
val Color.Companion.FIRE_BRICK by lazy { hex("#B22222") }
val Color.Companion.FLORAL_WHITE by lazy { hex("#FFFAF0") }
val Color.Companion.FOREST_GREEN by lazy { hex("#228B22") }
val Color.Companion.FUCHSIA by lazy { hex("#FF00FF") }
val Color.Companion.GAINSBORO by lazy { hex("#DCDCDC") }
val Color.Companion.GHOST_WHITE by lazy { hex("#F8F8FF") }
val Color.Companion.GOLD by lazy { hex("#FFD700") }
val Color.Companion.GOLDEN_ROD by lazy { hex("#DAA520") }
val Color.Companion.GRAY by lazy { hex("#808080") }
val Color.Companion.GREEN by lazy { hex("#008000") }
val Color.Companion.GREEN_YELLOW by lazy { hex("#ADFF2F") }
val Color.Companion.HONEY_DEW by lazy { hex("#F0FFF0") }
val Color.Companion.HOT_PINK by lazy { hex("#FF69B4") }
val Color.Companion.INDIAN_RED by lazy { hex("#CD5C5C") }
val Color.Companion.INDIGO by lazy { hex("#4B0082") }
val Color.Companion.IVORY by lazy { hex("#FFFFF0") }
val Color.Companion.KHAKI by lazy { hex("#FOE68C") }
val Color.Companion.LAVENDER by lazy { hex("#E6E6FA") }
val Color.Companion.LAVENDER_BLUSH by lazy { hex("#FFF0F5") }
val Color.Companion.LAWN_GREEN by lazy { hex("#7CFC00") }
val Color.Companion.LEMON_CHIFFON by lazy { hex("#FFFACD") }
val Color.Companion.LIGHT_BLUE by lazy { hex("#ADD8E6") }
val Color.Companion.LIGHT_CORAL by lazy { hex("#F08080") }
val Color.Companion.LIGHT_CYAN by lazy { hex("#E0FFFF") }
val Color.Companion.LIGHT_GOLDEN_ROD_YELLOW by lazy { hex("#FAFAD2") }
val Color.Companion.LIGHT_GRAY by lazy { hex("#D3D3D3") }
val Color.Companion.LIGHT_GREEN by lazy { hex("#90EE90") }
val Color.Companion.LIGHT_PINK by lazy { hex("#FFB6C1") }
val Color.Companion.LIGHT_SALMON by lazy { hex("#FFA07A") }
val Color.Companion.LIGHT_SEA_GREEN by lazy { hex("#20B2AA") }
val Color.Companion.LIGHT_SKY_BLUE by lazy { hex("#87CEFA") }
val Color.Companion.LIGHT_SLATE_GRAY by lazy { hex("#778899") }
val Color.Companion.LIGHT_SLATE_GREY by lazy { hex("#778899") }
val Color.Companion.LIGHT_STEEL_BLUE by lazy { hex("#B0C4DE") }
val Color.Companion.LIGHT_YELLOW by lazy { hex("#FFFFE0") }
val Color.Companion.LIME by lazy { hex("#00FF00") }
val Color.Companion.LIME_GREEN by lazy { hex("#32CD32") }
val Color.Companion.LINEN by lazy { hex("#FAF0E6") }
val Color.Companion.MAGENTA by lazy { hex("#FF00FF") }
val Color.Companion.MAROON by lazy { hex("#800000") }
val Color.Companion.MEDIUM_AQUA_MARINE by lazy { hex("#66CDAA") }
val Color.Companion.MEDIUM_BLUE by lazy { hex("#0000CD") }
val Color.Companion.MEDIUM_ORCHID by lazy { hex("#BA55D3") }
val Color.Companion.MEDIUM_PURPLE by lazy { hex("#9370DB") }
val Color.Companion.MEDIUM_SEA_GREEN by lazy { hex("#3CB371") }
val Color.Companion.MEDIUM_SLATE_BLUE by lazy { hex("#7B68EE") }
val Color.Companion.MEDIUM_SPRING_GREEN by lazy { hex("#00FA9A") }
val Color.Companion.MEDIUM_TURQUOISE by lazy { hex("#48D1CC") }
val Color.Companion.MEDIUM_VIOLET_RED by lazy { hex("#C71585") }
val Color.Companion.MIDNIGHT_BLUE by lazy { hex("#191970") }
val Color.Companion.MINT_CREAM by lazy { hex("#F5FFFA") }
val Color.Companion.MISTY_ROSE by lazy { hex("#FFE4E1") }
val Color.Companion.MOCCASIN by lazy { hex("#FFE4B5") }
val Color.Companion.NAVAJO_WHITE by lazy { hex("#FFDEAD") }
val Color.Companion.NAVY by lazy { hex("#000080") }
val Color.Companion.OLD_LACE by lazy { hex("#FDF5E6") }
val Color.Companion.OLIVE by lazy { hex("#808000") }
val Color.Companion.OLIVE_DRAB by lazy { hex("#6B8E23") }
val Color.Companion.ORANGE by lazy { hex("#FFA500") }
val Color.Companion.ORANGE_RED by lazy { hex("#FF4500") }
val Color.Companion.ORCHID by lazy { hex("#DA70D6") }
val Color.Companion.PALE_GOLDEN_ROD by lazy { hex("#EEE8AA") }
val Color.Companion.PALE_GREEN by lazy { hex("#98FB98") }
val Color.Companion.PALE_TURQUOISE by lazy { hex("#AFEEEE") }
val Color.Companion.PALE_VIOLET_RED by lazy { hex("#DB7093") }
val Color.Companion.PAPAYA_WHIP by lazy { hex("#FFEFD5") }
val Color.Companion.PEACH_PUFF by lazy { hex("#FFDAB9") }
val Color.Companion.PERU by lazy { hex("#CD853F") }
val Color.Companion.PINK by lazy { hex("#FFC0CB") }
val Color.Companion.PLUM by lazy { hex("#DDA0DD") }
val Color.Companion.POWDER_BLUE by lazy { hex("#B0E0E6") }
val Color.Companion.PURPLE by lazy { hex("#800080") }
val Color.Companion.REBECCA_PURPLE by lazy { hex("#663399") }
val Color.Companion.RED by lazy { hex("#FF0000") }
val Color.Companion.ROSY_BROWN by lazy { hex("#BC8F8F") }
val Color.Companion.ROYAL_BLUE by lazy { hex("#4169E1") }
val Color.Companion.SADDLE_BROWN by lazy { hex("#8B4513") }
val Color.Companion.SALMON by lazy { hex("#FA8072") }
val Color.Companion.SANDY_BROWN by lazy { hex("#F4A460") }
val Color.Companion.SEA_GREEN by lazy { hex("#2E8B57") }
val Color.Companion.SEA_SHELL by lazy { hex("#FFF5EE") }
val Color.Companion.SIENNA by lazy { hex("#A0522D") }
val Color.Companion.SILVER by lazy { hex("#C0C0C0") }
val Color.Companion.SKY_BLUE by lazy { hex("#87CEEB") }
val Color.Companion.SLATE_BLUE by lazy { hex("#6A5ACD") }
val Color.Companion.SLATE_GRAY by lazy { hex("#708090") }
val Color.Companion.SNOW by lazy { hex("#FFFAFA") }
val Color.Companion.SPRING_GREEN by lazy { hex("#00FF7F") }
val Color.Companion.STEEL_BLUE by lazy { hex("#4682B4") }
val Color.Companion.TAN by lazy { hex("#D2B48C") }
val Color.Companion.TEAL by lazy { hex("#008080") }
val Color.Companion.THISTLE by lazy { hex("#D8BFD8") }
val Color.Companion.TOMATO by lazy { hex("#FF6347") }
val Color.Companion.TURQUOISE by lazy { hex("#40E0D0") }
val Color.Companion.VIOLET by lazy { hex("#EE82EE") }
val Color.Companion.WHEAT by lazy { hex("#F5DEB3") }
val Color.Companion.WHITE_SMOKE by lazy { hex("#F5F5F5") }
val Color.Companion.YELLOW by lazy { hex("#FFFF00") }
val Color.Companion.YELLOW_GREEN by lazy { hex("#9ACD32") }
