@file:Suppress("unused")

package com.chrynan.colors.extension

import com.chrynan.colors.Color
import com.chrynan.colors.NamedColor

@ExperimentalUnsignedTypes
val Color.Companion.namedColors: Set<NamedColor>
    get() = setOf(
        NamedColor(name = "Black", color = BLACK),
        NamedColor(name = "White", color = WHITE),
        NamedColor(name = "Transparent", color = TRANSPARENT),
        NamedColor(name = "Alice Blue", color = Color.ALICE_BLUE),
        NamedColor(name = "Antique White", color = Color.ANTIQUE_WHITE),
        NamedColor(name = "Aqua Blue", color = Color.AQUA_BLUE),
        NamedColor(name = "Aquamarine", color = Color.AQUAMARINE),
        NamedColor(name = "Azure", color = Color.AZURE),
        NamedColor(name = "Beige", color = Color.BEIGE),
        NamedColor(name = "Bisque", color = Color.BISQUE),
        NamedColor(name = "Blanched Almond", color = Color.BLANCHED_ALMOND),
        NamedColor(name = "Blue", color = Color.BLUE),
        NamedColor(name = "Blue Violet", color = Color.BLUE_VIOLET),
        NamedColor(name = "Brown", color = Color.BROWN),
        NamedColor(name = "Burly Wood", color = Color.BURLY_WOOD),
        NamedColor(name = "Cadet Blue", color = Color.CADET_BLUE),
        NamedColor(name = "Chartreuse", color = Color.CHARTREUSE),
        NamedColor(name = "Chocolate", color = Color.CHOCOLATE),
        NamedColor(name = "Coral", color = Color.CORAL),
        NamedColor(name = "Cornflower Blue", color = Color.CORNFLOWER_BLUE),
        NamedColor(name = "Cornsilk", color = Color.CORNSILK),
        NamedColor(name = "Crimson", color = Color.CRIMSON),
        NamedColor(name = "Cyan", color = Color.CYAN),
        NamedColor(name = "Dark Blue", color = Color.DARK_BLUE),
        NamedColor(name = "Dark Cyan", color = Color.DARK_CYAN),
        NamedColor(name = "Dark Golden Rod", color = Color.DARK_GOLDEN_ROD),
        NamedColor(name = "Dark Gray", color = Color.DARK_GRAY),
        NamedColor(name = "Dark Green", color = Color.DARK_GREEN),
        NamedColor(name = "Dark Khaki", color = Color.DARK_KHAKI),
        NamedColor(name = "Dark Magenta", color = Color.DARK_MAGENTA),
        NamedColor(name = "Dark Olive Green", color = Color.DARK_OLIVE_GREEN),
        NamedColor(name = "Dark Orange", color = Color.DARK_ORANGE),
        NamedColor(name = "Dark Orchid", color = Color.DARK_ORCHID),
        NamedColor(name = "Dark Red", color = Color.DARK_RED),
        NamedColor(name = "Dark Salmon", color = Color.DARK_SALMON),
        NamedColor(name = "Dark Sea Green", color = Color.DARK_SEA_GREEN),
        NamedColor(name = "Dark Slate Blue", color = Color.DARK_SLATE_BLUE),
        NamedColor(name = "Dark Slate Gray", color = Color.DARK_SLATE_GRAY),
        NamedColor(name = "Dark Turquoise", color = Color.DARK_TURQUOISE),
        NamedColor(name = "Dark Violet", color = Color.DARK_VIOLET),
        NamedColor(name = "Deep Pink", color = Color.DEEP_PINK),
        NamedColor(name = "Deep Sky Blue", color = Color.DEEP_SKY_BLUE),
        NamedColor(name = "Dim Gray", color = Color.DIM_GRAY),
        NamedColor(name = "Dodger Blue", color = Color.DODGER_BLUE),
        NamedColor(name = "Fire Brick", color = Color.FIRE_BRICK),
        NamedColor(name = "Floral White", color = Color.FLORAL_WHITE),
        NamedColor(name = "Forest Green", color = Color.FOREST_GREEN),
        NamedColor(name = "Fuchsia", color = Color.FUCHSIA),
        NamedColor(name = "Gainsboro", color = Color.GAINSBORO),
        NamedColor(name = "Ghost White", color = Color.GHOST_WHITE),
        NamedColor(name = "Gold", color = Color.GOLD),
        NamedColor(name = "Golden Rod", color = Color.GOLDEN_ROD),
        NamedColor(name = "Gray", color = Color.GRAY),
        NamedColor(name = "Green", color = Color.GREEN),
        NamedColor(name = "Green Yellow", color = Color.GREEN_YELLOW),
        NamedColor(name = "Honey Dew", color = Color.HONEY_DEW),
        NamedColor(name = "Hot Pink", color = Color.HOT_PINK),
        NamedColor(name = "Indian Red", color = Color.INDIAN_RED),
        NamedColor(name = "Indigo", color = Color.INDIGO),
        NamedColor(name = "Ivory", color = Color.IVORY),
        NamedColor(name = "Khaki", color = Color.KHAKI),
        NamedColor(name = "Lavender", color = Color.LAVENDER),
        NamedColor(name = "Lavender Blush", color = Color.LAVENDER_BLUSH),
        NamedColor(name = "Lawn Green", color = Color.LAWN_GREEN),
        NamedColor(name = "Lemon Chiffon", color = Color.LEMON_CHIFFON),
        NamedColor(name = "Light Blue", color = Color.LIGHT_BLUE),
        NamedColor(name = "Light Coral", color = Color.LIGHT_CORAL),
        NamedColor(name = "Light Cyan", color = Color.LIGHT_CYAN),
        NamedColor(name = "Light Golden Rod Yellow", color = Color.LIGHT_GOLDEN_ROD_YELLOW),
        NamedColor(name = "Light Gray", color = Color.LIGHT_GRAY),
        NamedColor(name = "Light Green", color = Color.LIGHT_GREEN),
        NamedColor(name = "Light Pink", color = Color.LIGHT_PINK),
        NamedColor(name = "Light Salmon", color = Color.LIGHT_SALMON),
        NamedColor(name = "Light Sea Green", color = Color.LIGHT_SEA_GREEN),
        NamedColor(name = "Light Sky Blue", color = Color.LIGHT_SKY_BLUE),
        NamedColor(name = "Light Slate Gray", color = Color.LIGHT_SLATE_GRAY),
        NamedColor(name = "Light Steel Blue", color = Color.LIGHT_STEEL_BLUE),
        NamedColor(name = "Light Yellow", color = Color.LIGHT_YELLOW),
        NamedColor(name = "Lime", color = Color.LIME),
        NamedColor(name = "Lime Green", color = Color.LIME_GREEN),
        NamedColor(name = "Linen", color = Color.LINEN),
        NamedColor(name = "Magenta", color = Color.MAGENTA),
        NamedColor(name = "Maroon", color = Color.MAROON),
        NamedColor(name = "Medium Aqua Marine", color = Color.MEDIUM_AQUA_MARINE),
        NamedColor(name = "Medium Blue", color = Color.MEDIUM_BLUE),
        NamedColor(name = "Medium Orchid", color = Color.MEDIUM_ORCHID),
        NamedColor(name = "Medium Purple", color = Color.MEDIUM_PURPLE),
        NamedColor(name = "Medium Sea Green", color = Color.MEDIUM_SEA_GREEN),
        NamedColor(name = "Medium Slate Blue", color = Color.MEDIUM_SLATE_BLUE),
        NamedColor(name = "Medium Spring Green", color = Color.MEDIUM_SPRING_GREEN),
        NamedColor(name = "AMedium Turquoise", color = Color.MEDIUM_TURQUOISE),
        NamedColor(name = "Medium Violet Red", color = Color.MEDIUM_VIOLET_RED),
        NamedColor(name = "Medium Blue", color = Color.MIDNIGHT_BLUE),
        NamedColor(name = "Mint Cream", color = Color.MINT_CREAM),
        NamedColor(name = "Misty Rose", color = Color.MISTY_ROSE),
        NamedColor(name = "Moccasin", color = Color.MOCCASIN),
        NamedColor(name = "Navajo White", color = Color.NAVAJO_WHITE),
        NamedColor(name = "Navy", color = Color.NAVY),
        NamedColor(name = "Old Lace", color = Color.OLD_LACE),
        NamedColor(name = "Olive", color = Color.OLIVE),
        NamedColor(name = "Olive Drab", color = Color.OLIVE_DRAB),
        NamedColor(name = "Orange", color = Color.ORANGE),
        NamedColor(name = "Orange Red", color = Color.ORANGE_RED),
        NamedColor(name = "Orchid", color = Color.ORCHID),
        NamedColor(name = "Pale Golden Rod", color = Color.PALE_GOLDEN_ROD),
        NamedColor(name = "Pale Green", color = Color.PALE_GREEN),
        NamedColor(name = "Pale Turquoise", color = Color.PALE_TURQUOISE),
        NamedColor(name = "Pale Violet Red", color = Color.PALE_VIOLET_RED),
        NamedColor(name = "Papaya Whip", color = Color.PAPAYA_WHIP),
        NamedColor(name = "Peach Puff", color = Color.PEACH_PUFF),
        NamedColor(name = "Peru", color = Color.PERU),
        NamedColor(name = "Pink", color = Color.PINK),
        NamedColor(name = "Plum", color = Color.PLUM),
        NamedColor(name = "Powder Blue", color = Color.POWDER_BLUE),
        NamedColor(name = "Purple", color = Color.PURPLE),
        NamedColor(name = "Rebecca Purple", color = Color.REBECCA_PURPLE),
        NamedColor(name = "Red", color = Color.RED),
        NamedColor(name = "Rosy Brown", color = Color.ROSY_BROWN),
        NamedColor(name = "Royal Blue", color = Color.ROYAL_BLUE),
        NamedColor(name = "Saddle Brown", color = Color.SADDLE_BROWN),
        NamedColor(name = "Salmon", color = Color.SALMON),
        NamedColor(name = "Sandy Brown", color = Color.SANDY_BROWN),
        NamedColor(name = "Sea Green", color = Color.SEA_GREEN),
        NamedColor(name = "Sea Shell", color = Color.SEA_SHELL),
        NamedColor(name = "Sienna", color = Color.SIENNA),
        NamedColor(name = "Silver", color = Color.SILVER),
        NamedColor(name = "Sky Blue", color = Color.SKY_BLUE),
        NamedColor(name = "Slate Blue", color = Color.SLATE_BLUE),
        NamedColor(name = "Slate Gray", color = Color.SLATE_GRAY),
        NamedColor(name = "Snow", color = Color.SNOW),
        NamedColor(name = "Spring Green", color = Color.SPRING_GREEN),
        NamedColor(name = "Steel Blue", color = Color.STEEL_BLUE),
        NamedColor(name = "Tan", color = Color.TAN),
        NamedColor(name = "Teal", color = Color.TEAL),
        NamedColor(name = "Thistle", color = Color.THISTLE),
        NamedColor(name = "Tomato", color = Color.TOMATO),
        NamedColor(name = "Turquoise", color = Color.TURQUOISE),
        NamedColor(name = "Violet", color = Color.VIOLET),
        NamedColor(name = "Wheat", color = Color.WHEAT),
        NamedColor(name = "White Smoke", color = Color.WHITE_SMOKE),
        NamedColor(name = "Yellow", color = Color.YELLOW),
        NamedColor(name = "Yellow Green", color = Color.YELLOW_GREEN)
    )
