@file:Suppress("unused")

package com.chrynan.colors.extension

import com.chrynan.colors.Color
import com.chrynan.colors.NamedColor

val Color.Companion.namedColors: Set<NamedColor>
    get() = setOf(
        NamedColor(name = "Black", color = Black),
        NamedColor(name = "White", color = White),
        NamedColor(name = "Transparent", color = Transparent),
        NamedColor(name = "Alice Blue", color = Color.AliceBlue),
        NamedColor(name = "Antique White", color = Color.AntiqueWhite),
        NamedColor(name = "Aqua Blue", color = Color.AquaBlue),
        NamedColor(name = "Aquamarine", color = Color.Aquamarine),
        NamedColor(name = "Azure", color = Color.Azure),
        NamedColor(name = "Beige", color = Color.Beige),
        NamedColor(name = "Bisque", color = Color.Bisque),
        NamedColor(name = "Blanched Almond", color = Color.BlanchedAlmond),
        NamedColor(name = "Blue", color = Color.Blue),
        NamedColor(name = "Blue Violet", color = Color.BlueViolet),
        NamedColor(name = "Brown", color = Color.Brown),
        NamedColor(name = "Burly Wood", color = Color.BurlyWood),
        NamedColor(name = "Cadet Blue", color = Color.CadetBlue),
        NamedColor(name = "Chartreuse", color = Color.Chartreuse),
        NamedColor(name = "Chocolate", color = Color.Chocolate),
        NamedColor(name = "Coral", color = Color.Coral),
        NamedColor(name = "Cornflower Blue", color = Color.CornflowerBlue),
        NamedColor(name = "Cornsilk", color = Color.Cornsilk),
        NamedColor(name = "Crimson", color = Color.Crimson),
        NamedColor(name = "Cyan", color = Color.Cyan),
        NamedColor(name = "Dark Blue", color = Color.DarkBlue),
        NamedColor(name = "Dark Cyan", color = Color.DarkCyan),
        NamedColor(name = "Dark Golden Rod", color = Color.DarkGoldenRod),
        NamedColor(name = "Dark Gray", color = Color.DarkGray),
        NamedColor(name = "Dark Green", color = Color.DarkGreen),
        NamedColor(name = "Dark Khaki", color = Color.DarkKhaki),
        NamedColor(name = "Dark Magenta", color = Color.DarkMagenta),
        NamedColor(name = "Dark Olive Green", color = Color.DarkOliveGreen),
        NamedColor(name = "Dark Orange", color = Color.DarkOrange),
        NamedColor(name = "Dark Orchid", color = Color.DarkOrchid),
        NamedColor(name = "Dark Red", color = Color.DarkRed),
        NamedColor(name = "Dark Salmon", color = Color.DarkSalmon),
        NamedColor(name = "Dark Sea Green", color = Color.DarkSeaGreen),
        NamedColor(name = "Dark Slate Blue", color = Color.DarkSlateBlue),
        NamedColor(name = "Dark Slate Gray", color = Color.DarkSlateGray),
        NamedColor(name = "Dark Turquoise", color = Color.DarkTurquoise),
        NamedColor(name = "Dark Violet", color = Color.DarkViolet),
        NamedColor(name = "Deep Pink", color = Color.DeepPink),
        NamedColor(name = "Deep Sky Blue", color = Color.DeepSkyBlue),
        NamedColor(name = "Dim Gray", color = Color.DimGray),
        NamedColor(name = "Dodger Blue", color = Color.DodgerBlue),
        NamedColor(name = "Fire Brick", color = Color.FireBrick),
        NamedColor(name = "Floral White", color = Color.FloralWhite),
        NamedColor(name = "Forest Green", color = Color.ForestGreen),
        NamedColor(name = "Fuchsia", color = Color.Fuchsia),
        NamedColor(name = "Gainsboro", color = Color.Gainsboro),
        NamedColor(name = "Ghost White", color = Color.GhostWhite),
        NamedColor(name = "Gold", color = Color.Gold),
        NamedColor(name = "Golden Rod", color = Color.GoldenRod),
        NamedColor(name = "Gray", color = Color.Gray),
        NamedColor(name = "Green", color = Color.Green),
        NamedColor(name = "Green Yellow", color = Color.GreenYellow),
        NamedColor(name = "Honey Dew", color = Color.HoneyDew),
        NamedColor(name = "Hot Pink", color = Color.HotPink),
        NamedColor(name = "Indian Red", color = Color.IndianRed),
        NamedColor(name = "Indigo", color = Color.Indigo),
        NamedColor(name = "Ivory", color = Color.Ivory),
        NamedColor(name = "Khaki", color = Color.Khaki),
        NamedColor(name = "Lavender", color = Color.Lavender),
        NamedColor(name = "Lavender Blush", color = Color.LavenderBlush),
        NamedColor(name = "Lawn Green", color = Color.LawnGreen),
        NamedColor(name = "Lemon Chiffon", color = Color.LemonChiffon),
        NamedColor(name = "Light Blue", color = Color.LightBlue),
        NamedColor(name = "Light Coral", color = Color.LightCoral),
        NamedColor(name = "Light Cyan", color = Color.LightCyan),
        NamedColor(name = "Light Golden Rod Yellow", color = Color.LightGoldenRodYellow),
        NamedColor(name = "Light Gray", color = Color.LightGray),
        NamedColor(name = "Light Green", color = Color.LightGreen),
        NamedColor(name = "Light Pink", color = Color.LightPink),
        NamedColor(name = "Light Salmon", color = Color.LightSalmon),
        NamedColor(name = "Light Sea Green", color = Color.LightSeaGreen),
        NamedColor(name = "Light Sky Blue", color = Color.LightSkyBlue),
        NamedColor(name = "Light Slate Gray", color = Color.LightSlateGray),
        NamedColor(name = "Light Steel Blue", color = Color.LightSteelBlue),
        NamedColor(name = "Light Yellow", color = Color.LightYellow),
        NamedColor(name = "Lime", color = Color.Lime),
        NamedColor(name = "Lime Green", color = Color.LimeGreen),
        NamedColor(name = "Linen", color = Color.Linen),
        NamedColor(name = "Magenta", color = Color.Magenta),
        NamedColor(name = "Maroon", color = Color.Maroon),
        NamedColor(name = "Medium Aqua Marine", color = Color.MediumAquaMarine),
        NamedColor(name = "Medium Blue", color = Color.MediumBlue),
        NamedColor(name = "Medium Orchid", color = Color.MediumOrchid),
        NamedColor(name = "Medium Purple", color = Color.MediumPurple),
        NamedColor(name = "Medium Sea Green", color = Color.MediumSeaGreen),
        NamedColor(name = "Medium Slate Blue", color = Color.MediumSlateBlue),
        NamedColor(name = "Medium Spring Green", color = Color.MediumSpringGreen),
        NamedColor(name = "Medium Turquoise", color = Color.MediumTurquoise),
        NamedColor(name = "Medium Violet Red", color = Color.MediumVioletRed),
        NamedColor(name = "Medium Blue", color = Color.MidnightBlue),
        NamedColor(name = "Mint Cream", color = Color.MintCream),
        NamedColor(name = "Misty Rose", color = Color.MistyRose),
        NamedColor(name = "Moccasin", color = Color.Moccasin),
        NamedColor(name = "Navajo White", color = Color.NavajoWhite),
        NamedColor(name = "Navy", color = Color.Navy),
        NamedColor(name = "Old Lace", color = Color.OldLace),
        NamedColor(name = "Olive", color = Color.Olive),
        NamedColor(name = "Olive Drab", color = Color.OliveDrab),
        NamedColor(name = "Orange", color = Color.Orange),
        NamedColor(name = "Orange Red", color = Color.OrangeRed),
        NamedColor(name = "Orchid", color = Color.Orchid),
        NamedColor(name = "Pale Golden Rod", color = Color.PaleGoldenRod),
        NamedColor(name = "Pale Green", color = Color.PaleGreen),
        NamedColor(name = "Pale Turquoise", color = Color.PaleTurquoise),
        NamedColor(name = "Pale Violet Red", color = Color.PaleVioletRed),
        NamedColor(name = "Papaya Whip", color = Color.PapayaWhip),
        NamedColor(name = "Peach Puff", color = Color.PeachPuff),
        NamedColor(name = "Peru", color = Color.Peru),
        NamedColor(name = "Pink", color = Color.Pink),
        NamedColor(name = "Plum", color = Color.Plum),
        NamedColor(name = "Powder Blue", color = Color.PowderBlue),
        NamedColor(name = "Purple", color = Color.Purple),
        NamedColor(name = "Rebecca Purple", color = Color.RebeccaPurple),
        NamedColor(name = "Red", color = Color.Red),
        NamedColor(name = "Rosy Brown", color = Color.RosyBrown),
        NamedColor(name = "Royal Blue", color = Color.RoyalBlue),
        NamedColor(name = "Saddle Brown", color = Color.SaddleBrown),
        NamedColor(name = "Salmon", color = Color.Salmon),
        NamedColor(name = "Sandy Brown", color = Color.SandyBrown),
        NamedColor(name = "Sea Green", color = Color.SeaGreen),
        NamedColor(name = "Sea Shell", color = Color.SeaShell),
        NamedColor(name = "Sienna", color = Color.Sienna),
        NamedColor(name = "Silver", color = Color.Silver),
        NamedColor(name = "Sky Blue", color = Color.SkyBlue),
        NamedColor(name = "Slate Blue", color = Color.SlateBlue),
        NamedColor(name = "Slate Gray", color = Color.SlateGray),
        NamedColor(name = "Snow", color = Color.Snow),
        NamedColor(name = "Spring Green", color = Color.SpringGreen),
        NamedColor(name = "Steel Blue", color = Color.SteelBlue),
        NamedColor(name = "Tan", color = Color.Tan),
        NamedColor(name = "Teal", color = Color.Teal),
        NamedColor(name = "Thistle", color = Color.Thistle),
        NamedColor(name = "Tomato", color = Color.Tomato),
        NamedColor(name = "Turquoise", color = Color.Turquoise),
        NamedColor(name = "Violet", color = Color.Violet),
        NamedColor(name = "Wheat", color = Color.Wheat),
        NamedColor(name = "White Smoke", color = Color.WhiteSmoke),
        NamedColor(name = "Yellow", color = Color.Yellow),
        NamedColor(name = "Yellow Green", color = Color.YellowGreen)
    )
